name: Test

on: [push, pull_request]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install .

    - name: Install pytest
      run: pip install pytest

    - name: Build Docker Compose
      run: make build

    - name: Run Unit Tests
      run: pytest -vx --cov=app --cov-report term-missing --cov-fail-under=95
